### ISSUE TITLE
Problems loading the cereal archive under Windows

### ISSUE THREAD

**Issue by thomaskrause** [thomaskrause/graphANNIS#23]
Not all streams are marked as binary, which can lead to exceptions in Windows:

https://stackoverflow.com/questions/47766414/c-cereal-de-serialization-trouble-with-large-size-vector/47781987#47781987

This was originally reported by @sdruskat

**Comment by thomaskrause** [comment]
Closed in d4a73a6ab68eb5ace92c7d499b578415855c5ca7

**Comment by sdruskat** [comment]
Confirmed fixed for embedded version in [infraling/atomic](https://github.com/infraling/atomic). 0.6.0 also available from the p2 repository at http://corpus-tools.org/p2/.
